### PR TITLE
Add the types for forwardRef argument to styled()

### LINKED ISSUE #176: styled forwardRef argument works, but there are no types for it
Hi @cristianbote! Thanks for this project! This is probably just a simple oversight, but I've noticed that despite `styled` taking a second argument `forwardRef`, and it being documented as such, there are no types for that argument; [every version of the function](https://github.com/cristianbote/goober/blob/a630943ca6ccbb422607ee9dc0c28bec14be9429/goober.d.ts#L8) is typed as only taking a single argument. If I create a component using `styled as any`, the `forwardRef` argument behaves at runtime exactly as I expect.

### PR DESCRIPTION
**Pull request by michalczaplinski**
This adds updates the type declarations adding the types second argument to `styled()` - `forwardRef`.

I believe it's not possible to make the types more specific than a function that returns `any`

Fixes #176

### CODE REVIEW

**Comment by cristianbote** [comment]
woot, merge conflicts? 🤔

**Comment by michalczaplinski** [comment]
> woot, merge conflicts? 🤔

Looks like there was another PR with changes to the type declarations in the meantime 🙂 

BTW, looks like the changes in the README were applied by prettier automatically in the merge commit to make the spacing consistent in the file.

**Comment by michalczaplinski** [comment]
And PS. It's a nice little library you've created! 🙌

Discovered it while writing a researching for a blog post about CSS-in-JS.

**Review by cristianbote — APPROVED** [review]
Boom! 🎉 Awesome job!

**Comment by cristianbote** [comment]
Thank you @michalczaplinski and @devrnt for chasing this! 🙏 much appreciated! And thank you for your kind words @michalczaplinski 😄

**Pull request merged**
