### PR TITLE
feat: add transient props

### PR DESCRIPTION
**Pull request by devrnt**
Proposal for #203 

To be clear this `$` prefix could be anything even the 🥜 emoji

If this proposal would be approved there are still some things to be done
* [ ] Add documentation
* [ ] Add tests
* [ ] Add example in `ts-tests/test-api.tsx`

### CODE REVIEW

**Comment by cristianbote** [comment]
@devrnt thank you for opening this one! Much appreciate it! Size-wise it adds `+30B` which it's a bit much for goober's constraints, but was thinking if we could merge the `Object.assign` call and this one in a way that would have minimal impact?

**Comment by devrnt** [comment]
@cristianbote I don't know how we could move this in the `Object.assign` call.

Funny to see that only 30 bytes are resulting in a +2,65% size change. This small size of goober is just awesome, congrats!

**Comment by cristianbote** [comment]
Yeah it's a blessing but also a curse 😄  lol.

Regarding the transient props. Do you think we could have a test that would check for their integration? Meaning that `React` will complain or something like that?

**Comment by devrnt** [comment]
I don't know how you would intercept React error logs in a test environment.

**Comment by cristianbote** [comment]
@devrnt #212 will shave some `-12B` from the bundle. 😄  do you have ideas if we could achieve it that? 🤔

**Comment by devrnt** [comment]
@cristianbote I don't understand your sentence? You mean like shaving a few more bytes in this PR?

**Comment by dqbd** [comment]
There might be some spare change in terms of file size optimalization (replacing const with let, defining object right at the top), but I suppose every byte counts? 😄 :

```
let _props = Object.assign(props), _previousProps = {};

...

for (let key in _props) {
    if (key[0] !== "$") {
        _previousProps[key] = _props[key]
    } 
}
```

**Pull request closed without merging**
