### PR TITLE
remove g flag from regex test

### PR DESCRIPTION
**Pull request by iguessitsokay**
g flag is counter-productive for .test() method with single use regex instances. one match should be conclusive.

### CODE REVIEW

**Comment by cristianbote** [comment]
woop woop! You got this, @iguessitsokay! 🎉  Nice findings!

**Comment by cristianbote** [comment]
@iguessitsokay this is rock solid! Thank you so much for opening this up! Do you wanna snoop around more? If not let me know, and we can merge this in!

**Comment by iguessitsokay** [comment]
@christianbote thank you, sorry for the late return. I think better merge this. gzip is not getting smaller, yet.

**Comment by cristianbote** [comment]
Thank you so much for your submission @iguessitsokay! Don't forget to submit and expense for your shaved bytes! https://opencollective.com/goober/expenses/new

**Pull request merged**
