### PR TITLE
Code golf update (-2B)

### PR DESCRIPTION
**Pull request by penge**
This is a small improvement that shaves 2B. Together with https://github.com/cristianbote/goober/pull/333 it would make 10B.

**Before:**

```
1173 B: goober.js.gz
1065 B: goober.js.br
1181 B: goober.modern.js.gz
1074 B: goober.modern.js.br
1181 B: goober.esm.js.gz
1074 B: goober.esm.js.br
1241 B: goober.umd.js.gz
1120 B: goober.umd.js.br
```

**Now:**

```
1171 B: goober.js.gz
1061 B: goober.js.br
1179 B: goober.modern.js.gz
1070 B: goober.modern.js.br
1179 B: goober.esm.js.gz
1070 B: goober.esm.js.br
1238 B: goober.umd.js.gz
1114 B: goober.umd.js.br
```

Difference: **-2B**
Difference together with https://github.com/cristianbote/goober/pull/333: **-10B**

### CODE REVIEW

**Comment by rschristian** [comment]
It's probably worth noting that `indexOf()` is considerably faster than `includes()` on all platforms, as far as I can tell. As Goober is absurdly fast as well as small, that perf drop might be a greater loss than the two bytes.

**Comment by cristianbote** [comment]
Hey @penge thank you for taking a look and opening this one. I believe @rschristian is right, usually `indexOf` is faster. Have you seen some perf degradation in that regard? More exactly the `test-perf` task what does it report?

**Comment by rschristian** [comment]
Yeah I had ran the test to confirm, and saw a bit of degredation, but apparently I forgot to copy down the results here. Whoops!

Rerunning now, after a few runs, this PR:

```
Starting: styled:object
▸ goober x 267,805 ops/sec ±1.76% (84 runs sampled)
▸ styled-components@5.2.1 x 16,120 ops/sec ±8.63% (49 runs sampled)
▸ emotion@11.0.0 x 98,366 ops/sec ±4.49% (75 runs sampled)

Fastest is: goober

Starting: styled:tagged
▸ goober x 216,000 ops/sec ±5.73% (80 runs sampled)
▸ styled-components@5.2.1 x 10,076 ops/sec ±2.78% (80 runs sampled)
▸ emotion@11.0.0 x 119,973 ops/sec ±4.25% (73 runs sampled)

Fastest is: goober

Starting: styled:array
▸ goober x 219,112 ops/sec ±5.80% (79 runs sampled)
▸ styled-components@5.2.1 x 6,969 ops/sec ±1.16% (89 runs sampled)
▸ emotion@11.0.0 x 120,353 ops/sec ±2.80% (85 runs sampled)

Fastest is: goober
```

While the current state of `master` results in:

```
Starting: styled:object
▸ goober x 264,334 ops/sec ±1.80% (84 runs sampled)
▸ styled-components@5.2.1 x 16,625 ops/sec ±8.45% (46 runs sampled)
▸ emotion@11.0.0 x 130,173 ops/sec ±2.82% (83 runs sampled)

Fastest is: goober

Starting: styled:tagged
▸ goober x 269,998 ops/sec ±2.35% (84 runs sampled)
▸ styled-components@5.2.1 x 9,958 ops/sec ±2.36% (83 runs sampled)
▸ emotion@11.0.0 x 140,436 ops/sec ±1.75% (80 runs sampled)

Fastest is: goober

Starting: styled:array
▸ goober x 222,941 ops/sec ±4.71% (82 runs sampled)
▸ styled-components@5.2.1 x 6,818 ops/sec ±0.96% (89 runs sampled)
▸ emotion@11.0.0 x 115,942 ops/sec ±2.74% (80 runs sampled)

Fastest is: goober
```

Seems like a decent sized chunk was taken out of styled:tagged, and with my own tests of `includes()` vs. `indexOf()`, this lines up with my expectations.

That being said, I'm not a regular here, just was browsing through; you know your benchmark suite better than I do. I ran it a few times to try to ensure a consistent result, but it very well could be just a few outliers I'm seeing.

**Comment by penge** [comment]
I think based on the slight degredation we can close this one as the speed is more important.
Thank you @rschristian for the test.

I believe @cristianbote would agree too. Thank you both.

**Pull request closed without merging**
