### PR TITLE
(feat) Conditional styles with array as argument

### PR DESCRIPTION
**Pull request by cristianbote**
This is a new way, for goober, to define your conditional styling based on an array of objects or array of functions.

cc @ben-rogerson

### CODE REVIEW

**Comment by ben-rogerson** [comment]
Thanks so much for adding this feature. I've tested it's all working great!

I also tested with `babel-plugin-transform-goober` but to add [twin](https://github.com/ben-rogerson/twin.macro) support the plugin must allow working with a renamed import from styled (eg: `import { styled as renamedImport } from 'goober'`). 
I have that feature working locally and I'll submit a pr shortly.

**Comment by ben-rogerson** [comment]
I found a small issue:

image

The error shows when the array item equals `undefined`, like this:

```js
const Button = styled('button')(({ isPrimary }) => [
  isPrimary && {
    backgroundColor: 'green'
  }
])

const App = () => (
    <Button>Send</Button>
)
```

Perhaps you could check if `i` is defined before the merge here?

```js
_val.reduce((o, i) => Object.assign(o, i.call ? i(ctx.p) : i))
```

**Comment by cristianbote** [comment]
@ben-rogerson great catch! Let me add that suggestion.

**Comment by cristianbote** [comment]
Published `2.0.14` with this

**Comment by ben-rogerson** [comment]
Found an issue, possibly related #199

**Pull request merged**
